apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-video-app
spec:
  replicas: 1
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 200
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: discord-bot
          image: "{{ .Values.images.discordBot.repository }}:{{ .Values.images.discordBot.tag }}"
          imagePullPolicy: "{{ .Values.images.discordBot.pullPolicy }}"
          env:
            - name: NODE_ENV
              value: "{{ .Values.environment }}"
          resources:
            {{- toYaml .Values.resources.discordBot | nindent 12 }}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30