apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-media
  namespace: discord-video-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codex-media
  template:
    metadata:
      labels:
        app: codex-media
    spec:
      containers:
        - name: codex-media
          image: "{{ .Values.images.codexMedia.repository }}:{{ .Values.images.codexMedia.tag }}"
          imagePullPolicy: "{{ .Values.images.codexMedia.pullPolicy }}"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
