steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/Dokbawi/discord-video-helm.git"]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        mkdir -p env

        gcloud secrets versions access latest --secret="rabbitmq-password" > env/rabbitmq-password

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Bitnami 리포지토리 추가
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo update

        # 의존성 업데이트
        helm dependency update

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # GKE 인증
        gcloud container clusters get-credentials ${_CLUSTER_NAME} --location=${_CLUSTER_LOCATION}

        RABBIT_PASSWORD=$(cat env/rabbitmq-password)

        # Helm 배포 (프로덕션 환경만)
        helm upgrade --install discord-video . \
          --namespace=prod \
          --create-namespace \
          --values=values.yaml \
          --set mongodb.auth.rootPassword="${MONGO_PASSWORD}" \
          --set rabbitmq.auth.password="${RABBIT_PASSWORD}" \
          --set images.discordBot.tag="${_DISCORD_BOT_TAG}" \
          --set images.winterCatVideo.tag="${_WINTER_CAT_TAG}" \
          --set images.codexMedia.tag="${_CODEX_MEDIA_TAG}" \
          --wait --timeout=10m

        # 배포 상태 확인
        kubectl get pods -n prod
        kubectl get services -n prod

substitutions:
  _CLUSTER_NAME: "discord-bot-app-k8s"
  _CLUSTER_LOCATION: "asia-northeast3-a"
  _DISCORD_BOT_TAG: "latest"
  _WINTER_CAT_TAG: "latest"
  _CODEX_MEDIA_TAG: "latest"

options:
  logging: CLOUD_LOGGING_ONLY
