images:
  discordBot:
    repository: gcr.io/directed-strata-447305-p6/discord-bot
    tag: latest
    pullPolicy: Always
  winterCatVideo:
    repository: gcr.io/directed-strata-447305-p6/winter-cat-video
    tag: latest
    pullPolicy: Always
  codexMedia:
    repository: gcr.io/directed-strata-447305-p6/codex-media
    tag: latest
    pullPolicy: Always

environment: production
namespace: prod

resources:
  discordBot:
    requests:
      memory: "256Mi"
      cpu: "100m"
  winterCatVideo:
    requests:
      memory: "256Mi"
      cpu: "100m"
  codexMedia:
    requests:
      memory: "512Mi"
      cpu: "250m"

service:
  winterCatVideo:
    type: ClusterIP
    port: 3000
    nodePort: 3000
  codexMedia:
    type: ClusterIP
    port: 3002
