imagePullSecrets:
  - name: ecr-secret

images:
  discordBot:
    repository: 613890646734.dkr.ecr.ap-southeast-2.amazonaws.com/winter-cat
    tag: discord-bot-latest
    pullPolicy: Always
  winterCatVideo:
    repository: 613890646734.dkr.ecr.ap-southeast-2.amazonaws.com/winter-cat
    tag: winter-cat-video-latest
    pullPolicy: Always
  codexMedia:
    repository: 613890646734.dkr.ecr.ap-southeast-2.amazonaws.com/winter-cat
    tag: codex-media-latest
    pullPolicy: Always

environment: production

resources:
  discordBot:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  winterCatVideo:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  codexMedia:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "300m"

service:
  winterCatVideo:
    type: NodePort
    port: 3000
    nodePort: 30000
  codexMedia:
    type: ClusterIP
    port: 3002
