apiVersion: apps/v1
kind: Deployment
metadata:
  name: winter-cat-video
  namespace: discord-video-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: winter-cat-video
  template:
    metadata:
      labels:
        app: winter-cat-video
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: winter-cat-video
          image: "{{ .Values.images.winterCatVideo.repository }}:{{ .Values.images.winterCatVideo.tag }}"
          imagePullPolicy: "{{ .Values.images.winterCatVideo.pullPolicy }}"
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "{{ .Values.environment }}"
          resources:
            {{- toYaml .Values.resources.winterCatVideo | nindent 12 }}