apiVersion: v1
kind: Service
metadata:
  name: winter-cat-video-service
  namespace: discord-video-app
spec:
  selector:
    app: winter-cat-video
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
