apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets-system

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets-system

resources:
  - https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/charts/external-secrets/crds/bundle.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 0.9.11
    namespace: external-secrets-system
    includeCRDs: true
