apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: discord-video-app
  labels:
    app: rabbitmq
    component: infrastructure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      serviceAccountName: gke-registry-sa@directed-strata-447305-p6.iam.gserviceaccount.com
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          command: ["/bin/bash", "-c"]
          args:
            - |
              export RABBIT_PASS=$(gcloud secrets versions access latest --secret=rabbitmq-password)
              export RABBITMQ_DEFAULT_USER=admin
              export RABBITMQ_DEFAULT_PASS=$RABBIT_PASS
              exec docker-entrypoint.sh rabbitmq-server
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /api/health/checks/alarms
              port: 15672
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health/checks/local-alarms
              port: 15672
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: discord-video-app
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: LoadBalancer
