apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: gcpsm-secret-store
    kind: SecretStore
  target:
    name: argocd-initial-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: argocd-admin-password
